# Generated by Django 5.1.1 on 2024-09-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='coapplicatincome',
            new_name='coapplicantincome',
        ),
    ]
